# from .alpha import *
#
# __all__ = ['tech_factors', 'patn_factors']
#
# # 技术指标
# tech_factors = {
#     'Tech_ATR_Factor': Tech_ATR_Factor(),
#     'Tech_CCI_Factor': Tech_CCI_Factor(),
#     'Tech_MFI_Factor': Tech_MFI_Factor(),
#     'Tech_ROC_Factor': Tech_ROC_Factor(),
#     'Tech_RSI_Factor': Tech_RSI_Factor(),
#     'Tech_WILLR_Factor': Tech_WILLR_Factor(),
#     'Tech_CHO_Factor': Tech_CHO_Factor(),
#     'Tech_TRIX_Factor': Tech_TRIX_Factor(),
#     'Tech_OBV_Factor': Tech_OBV_Factor(),
#     'Tech_MA_Factor': Tech_MA_Factor(),
#     'Tech_EMA_Factor': Tech_EMA_Factor(),
#     'Tech_KAMA_Factor': Tech_KAMA_Factor()
# }
#
# # 形态指标
# patn_factors = {
#     'Patn_2CROWS_Factor': Patn_2CROWS_Factor(),
#     'Patn_3BLACKCROWS_Factor': Patn_3BLACKCROWS_Factor(),
#     'Patn_3INSIDE_Factor': Patn_3INSIDE_Factor(),
#     'Patn_3LINESTRIKE_Factor': Patn_3LINESTRIKE_Factor(),
#     'Patn_3OUTSIDE_Factor': Patn_3OUTSIDE_Factor(),
#     'Patn_3STARSINSOUTH_Factor': Patn_3STARSINSOUTH_Factor(),
#     'Patn_3WHITESOLDIERS_Factor': Patn_3WHITESOLDIERS_Factor(),
#     'Patn_ABANDONEDBABY_Factor': Patn_ABANDONEDBABY_Factor(),
#     'Patn_ADVANCEBLOCK_Factor': Patn_ADVANCEBLOCK_Factor(),
#     'Patn_BELTHOLD_Factor': Patn_BELTHOLD_Factor(),
#     'Patn_BREAKAWAY_Factor': Patn_BREAKAWAY_Factor(),
#     'Patn_CLOSINGMARUBOZU_Factor': Patn_CLOSINGMARUBOZU_Factor(),
#     'Patn_CONCEALBABYSWALL_Factor': Patn_CONCEALBABYSWALL_Factor(),
#     'Patn_COUNTERATTACK_Factor': Patn_COUNTERATTACK_Factor(),
#     'Patn_DARKCLOUDCOVER_Factor': Patn_DARKCLOUDCOVER_Factor(),
#     'Patn_DOJI_Factor': Patn_DOJI_Factor(),
#     'Patn_DOJISTAR_Factor': Patn_DOJISTAR_Factor(),
#     'Patn_DRAGONFLYDOJI_Factor': Patn_DRAGONFLYDOJI_Factor(),
#     'Patn_ENGULFING_Factor': Patn_ENGULFING_Factor(),
#     'Patn_EVENINGDOJISTAR_Factor': Patn_EVENINGDOJISTAR_Factor(),
#     'Patn_EVENINGSTAR_Factor': Patn_EVENINGSTAR_Factor(),
#     'Patn_GAPSIDESIDEWHITE_Factor': Patn_GAPSIDESIDEWHITE_Factor(),
#     'Patn_GRAVESTONEDOJI_Factor': Patn_GRAVESTONEDOJI_Factor(),
#     'Patn_HAMMER_Factor': Patn_HAMMER_Factor(),
#     'Patn_HANGINGMAN_Factor': Patn_HANGINGMAN_Factor(),
#     'Patn_HARAMI_Factor': Patn_HARAMI_Factor(),
#     'Patn_HARAMICROSS_Factor': Patn_HARAMICROSS_Factor(),
#     'Patn_HIGHWAVE_Factor': Patn_HIGHWAVE_Factor(),
#     'Patn_HIKKAKE_Factor': Patn_HIKKAKE_Factor(),
#     'Patn_HIKKAKEMOD_Factor': Patn_HIKKAKEMOD_Factor(),
#     'Patn_HOMINGPIGEON_Factor': Patn_HOMINGPIGEON_Factor(),
#     'Patn_IDENTICAL3CROWS_Factor': Patn_IDENTICAL3CROWS_Factor(),
#     'Patn_INNECK_Factor': Patn_INNECK_Factor(),
#     'Patn_INVERTEDHAMMER_Factor': Patn_INVERTEDHAMMER_Factor(),
#     'Patn_KICKING_Factor': Patn_KICKING_Factor(),
#     'Patn_KICKINGBYLENGTH_Factor': Patn_KICKINGBYLENGTH_Factor(),
#     'Patn_LADDERBOTTOM_Factor': Patn_LADDERBOTTOM_Factor(),
#     'Patn_LONGLEGGEDDOJI_Factor': Patn_LONGLEGGEDDOJI_Factor(),
#     'Patn_LONGLINE_Factor': Patn_LONGLINE_Factor(),
#     'Patn_MARUBOZU_Factor': Patn_MARUBOZU_Factor(),
#     'Patn_MATCHINGLOW_Factor': Patn_MATCHINGLOW_Factor(),
#     'Patn_MATHOLD_Factor': Patn_MATHOLD_Factor(),
#     'Patn_MORNINGSTAR_Factor': Patn_MORNINGSTAR_Factor(),
#     'Patn_MORNINGDOJISTAR_Factor': Patn_MORNINGDOJISTAR_Factor(),
#     'Patn_ONNECK_Factor': Patn_ONNECK_Factor(),
#     'Patn_PIERCING_Factor': Patn_PIERCING_Factor(),
#     'Patn_RICKSHAWMAN_Factor': Patn_RICKSHAWMAN_Factor(),
#     'Patn_RISEFALL3METHODS_Factor': Patn_RISEFALL3METHODS_Factor(),
#     'Patn_SEPARATINGLINES_Factor': Patn_SEPARATINGLINES_Factor(),
#     'Patn_SHOOTINGSTAR_Factor': Patn_SHOOTINGSTAR_Factor(),
#     'Patn_SHORTLINE_Factor': Patn_SHORTLINE_Factor(),
#     'Patn_SPINNINGTOP_Factor': Patn_SPINNINGTOP_Factor(),
#     'Patn_STALLEDPATTERN_Factor': Patn_STALLEDPATTERN_Factor(),
#     'Patn_STICKSANDWICH_Factor': Patn_STICKSANDWICH_Factor(),
#     'Patn_TAKURI_Factor': Patn_TAKURI_Factor(),
#     'Patn_TASUKIGAP_Factor': Patn_TASUKIGAP_Factor(),
#     'Patn_THRUSTING_Factor': Patn_THRUSTING_Factor(),
#     'Patn_TRISTAR_Factor': Patn_TRISTAR_Factor(),
#     'Patn_UNIQUE3RIVER_Factor': Patn_UNIQUE3RIVER_Factor(),
#     'Patn_UPSIDEGAP2CROWS_Factor': Patn_UPSIDEGAP2CROWS_Factor(),
#     'Patn_XSIDEGAP3METHODS_Factor': Patn_XSIDEGAP3METHODS_Factor()
# }
